In [36]:
import numpy as np
array=np.array([1,4,6,7])
print(array)
list1=[1,4,6]
list2=[1,4,6]
list3=[1,4,6]
arr=np.array([list1,list2,list3])
arr

[1 4 6 7]


array([[1, 4, 6],
       [1, 4, 6],
       [1, 4, 6]])

In [37]:
array[1:-1]

array([4, 6])

In [39]:
array[::-2]

array([7, 4])

In [49]:
arr[:,1:3]  #accessing all rows amd column 2

array([[4, 6],
       [4, 6],
       [4, 6]])

In [50]:
arr[:,2]

array([6, 6, 6])

In [53]:
arr[:,1:]

array([[4, 6],
       [4, 6],
       [4, 6]])

In [55]:
arr[:,::2]

array([[1, 6],
       [1, 6],
       [1, 6]])

In [66]:
print(array<=4)
array[array<=4]

[ True  True False False]


array([1, 4])

In [67]:
array.reshape(2,2)

array([[1, 4],
       [6, 7]])

In [9]:
mat=np.matrix([[1,2][1,3]])
mat

matrix([[1, 2],
        [1, 3]])

In [10]:
mat.shape

(2, 2)

matrix([[1, 2]])

In [72]:
np.arange(1,10,3)

array([1, 4, 7])

In [74]:
array**array # ** is power form

array([     1,    256,  46656, 823543])

In [80]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
np.zeros_like((3,5))

array([0, 0])

In [84]:
np.random.randn(2,4)

array([[-1.16646806, -0.64865841,  0.6687412 , -1.23763615],
       [ 1.26017718,  0.2672632 , -0.26024748, -0.67315069]])